import random,string

##autogenerated edp_id 
def edp_id_generator(size=12, chars=string.ascii_uppercase + string.digits): ##autogenerated edp_id of educationprofile table
        return ''.join(random.choice(chars) for _ in range(size))
## auto generate OTP
def otp_generate(size=6,chars=string.digits): ##auto generate OTP
        return "".join(random.choice(chars) for _ in range(size))
##autogenerated course_id 
def course_id_generator(size=12, chars=string.ascii_uppercase + string.digits): ##autogenerated course_id of course table
        return ''.join(random.choice(chars) for _ in range(size))