# Generated by Django 5.1.2 on 2024-10-14 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('duration', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('deg', 'Degree'), ('cert', 'Certificates')], default='cert', max_length=4)),
                ('medium', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('EIC_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual')], default='individual', max_length=12)),
                ('Location', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('IIC_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University')], default='school', max_length=10)),
                ('location', models.CharField(max_length=15)),
                ('Acc_status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('skill_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=20)),
                ('Level', models.CharField(choices=[('beg', 'Beginner'), ('int', 'Intermediate'), ('adv', 'Advanced')], default='beg', max_length=3)),
                ('Feature', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('MEC_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('Address', models.TextField(blank=True, null=True)),
                ('Guardian', models.ManyToManyField(blank=True, related_name='guardians', to='dashboard.citizen')),
                ('skills', models.ManyToManyField(blank=True, related_name='skillset', to='dashboard.skillset')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('edp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qualifications', models.CharField(max_length=20)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=9)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.citizen')),
                ('Inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.institution')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ManyToManyField(related_name='institutions_available', to='dashboard.institution'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('intern', 'Internship'), ('ft', 'Full-Time'), ('pt', 'Part-Time'), ('fl', 'Freelancing')], default='fl', max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employer')),
                ('skills_req', models.ManyToManyField(related_name='skills_required', to='dashboard.skillset')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentProfile',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('resigned', 'Resigned'), ('promoted', 'Promoted')], default='ongoing', max_length=9)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.citizen')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employer')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.job')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('review', 'In-Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='review', max_length=8)),
                ('date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.citizen')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.job')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(related_name='skills_offered', to='dashboard.skillset'),
        ),
    ]
