# Generated by Django 5.1.2 on 2024-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofile',
            name='department',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='registration_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='roll',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
