# Generated by Django 5.1.2 on 2024-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_educationprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofile',
            name='registration_no',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
