# Generated by Django 5.1.2 on 2024-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_educationprofile_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprofile',
            name='registration_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
