# Generated by Django 5.1.2 on 2024-11-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
