# Generated by Django 5.1.3 on 2024-11-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_course_totalsem_alter_course_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(default=0, upload_to='institute/logo'),
            preserve_default=False,
        ),
    ]
