# Generated by Django 5.1.3 on 2024-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
