# Generated by Django 5.1.3 on 2024-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_institution_location_alter_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='profile_img',
            field=models.ImageField(default=0, upload_to='citizen/profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem1',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem2',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem3',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem4',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem5',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem6',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem7',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='sem8',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='ten_grade',
            field=models.FileField(default=0, upload_to='citizen/grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='twelve_grade',
            field=models.FileField(default=0, upload_to='citizen/grade'),
            preserve_default=False,
        ),
    ]
