# Generated by Django 5.1.3 on 2024-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_citizen_profile_img_citizen_sem1_citizen_sem2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='sem1',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem2',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem3',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem4',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem5',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem6',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem7',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='sem8',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='ten_grade',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='twelve_grade',
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem1',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem2',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem3',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem4',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem5',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem6',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem7',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='sem8',
            field=models.FileField(default=0, upload_to='citizen/sem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='ten_grade',
            field=models.FileField(default=0, upload_to='citizen/grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='twelve_grade',
            field=models.FileField(default=0, upload_to='citizen/grade'),
            preserve_default=False,
        ),
    ]
