# Generated by Django 5.1.3 on 2024-11-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_citizen_sem1_remove_citizen_sem2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='Guardian',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
    ]
