# Generated by Django 5.1.3 on 2024-11-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_citizen_guardian_remove_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofile',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationprofile',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='edp_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
